### ISSUE TITLE
Two small comments about ansible-directory.tar.gz

### ISSUE THREAD

**Issue by jpmens** [possnfiffer/bsd-pw#5]
I was glancing at your excellent workshop and was curious about the content of `ansible-directory.tar.gz` so I downloaded it. If you don't mind, I've a two comments:

1. You specify `ansible_python_interpreter` in the `hosts` inventory file, which is fine, but you might like to "hide" that from your students by configuring `interpreter_python` in the `[defaults]` of `ansible.cfg` instead.
2. The tgz contains two unnecessary files `./.hosts.un~` and `./group_vars/all/.config.un~`

**Comment by possnfiffer** [comment]
@jpmens Thanks for your feedback. I've incorporated it into the `ansible-directory.tar.gz`
